server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
    password: admin
  application:
    name: service-plazoleta

  jpa:
    hibernate:
      ddl-auto: update

